/*
require('./tests/users')
require('./tests/files')
require('./tests/rooms')
require('./tests/fields')
require('./tests/roles')
require('./tests/objects')
require('./tests/directories')
require('./tests/tags')
require('./tests/profile')
require('./tests/api')
require('./tests/items')
*/
require('./tests/chat')